### ISSUE TITLE
Installer command fails to install pkg in M1 macOS without Rosetta

### ISSUE THREAD

**Issue by ningziwen** [runfinch/finch#105]
**Describe the bug**
Current aarch64 installer can't be installed by installer command in M1 macOS without Rosetta installed.

**Steps to reproduce**
1. Get a fresh M1 macOS host without Rosetta installed. (For example use macOS EC2: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-mac-instances.html)
2. Run `/usr/bin/pgrep -q oahd && echo Yes || echo No` to validate Rosetta is not installed. "No" means it is not installed.
3. Run `sudo installer -pkg <aarch64 installer pkg path> -target /`

**Expected behavior**
Installation succeeds.

**Screenshots or logs**

```
~ % sudo installer -pkg Finch-v0.1.1-aarch64.pkg -target /
installer: This package requires Rosetta 2 to be installed.
                Please install Rosetta 2 and then try again.
                    `sudo softwareupdate --install-rosetta`

installer: Error - Finch can’t be installed on this computer.
```

**Additional context**
Found this [thread](https://developer.apple.com/forums/thread/667672). This might be fixed by specifying hostArchitectures in installer.

**Comment by KevinLiAWS** [comment]
Fixed by release v0.2.0 https://github.com/runfinch/finch/releases/tag/v0.2.0
