### ISSUE TITLE
First time of running Finch command after installation triggered by Github action fails in arm64 runners

### ISSUE THREAD

**Issue by ningziwen** [runfinch/finch#106]
**Describe the bug**
First time of running Finch command after installation triggered by Github action fails in arm64 runners.
Only happens at the first time before any successful command call after installation. (Failed command call doesn't help so retry doesn't work)
Only happens when it is triggerd by Github action.
Only happens in arm64 runners.

See additional contexts for more experiments.

**Steps to reproduce**
Run the "release-installer" workflow, or restart the [workflow](https://github.com/runfinch/finch/actions/runs/3605504495/jobs/6075968565) to run the simplified version.

Currently only the members could run them. If you are interested in reproducing this but you are not member, you could add your own self-hosted runners to your forked repo and run with them.

**Expected behavior**
The command should succeed.

**Screenshots or logs**
Simplified workflow failure: https://github.com/runfinch/finch/actions/runs/3605504495/jobs/6075968565
```
Run finch version
/Users/ec2-user/ar/_work/_temp/1c6f50b2-a657-4625-99f4-4b80cce4f856.sh: line 1: 57022 Killed: 9               finch version
Error: Process completed with exit code [13](https://github.com/runfinch/finch/actions/runs/3605504495/jobs/6075968565#step:8:14)7.
```

**Additional context**

Confirmed the user used by github action is "ec2-user" by printing the user in Github action.
Confirmed the path of "finch" is from "/Applications/Finch/bin/finch" by running "which" and "readlink" commands in Github action.

Here are the experiements I did.

Succeeded scenarioes:
1. first time of running`finch version` after installation triggered by Github action in amd64 hosts with macOS version 10/11/12/13
2. running "ls" triggered by Github action in arm64 hosts
3. After installation (not matter triggered by Github action or manual action in ssh), ssh to the host and manually run `finch version`.
4. After installation (not matter triggered by Github action or manual action in ssh), ssh to the host and manually run `finch version` for one time. Then run an Github action that only runs `finch version` in arm64 hosts.

Failed scenarioes (by same 137 error):
1. first time of running`finch version` after installation triggered by Github action in arm64 hosts with macOS version 11/12/13 (arm64 is not supported with macOS version 10)
2. Set `permissions:contents:write-all` in yaml. Others are same as 1.
3. After installation (not matter triggered by Github action or manual action in ssh), ssh to the host and manually run `finch version` for one time. Then run an Github action that re-installs and then runs `finch version` in arm64 hosts.
4. Add 30s sleep before running `finch version` and after installation in yaml. Others are same as 1.
5. Add retry for `finch version` in Github action. Others are same as 1.

Some directions for further investigation:
1. Try to make Finch .app to see if it can resolve. https://superuser.com/a/28400
2. As `finch version` can already reproduce the issue, which doesn't require any deep dependencies, maybe we can minimize an application to reproduce this. For example, create a cobra application with version command only, and make it a macOS installer. Try to run the `version` command in the workflow to see if it can be reproduced. It can't, the cause must be in the incrementals from the minimum application to the full Finch. Slightly increment the features related to `version` command until it can be reproduced. If it can be reproduced with the minimum application, we can probably cut tickets to Github action or Cobra.

**Comment by KevinLiAWS** [comment]
The issue was fixed in 0.3.0
