### ISSUE TITLE
Error building hello-finch

### ISSUE THREAD

**Issue by strategicpause** [runfinch/finch#111]
**Describe the bug**
I've recently installed Finch on MacOS Monterrey and ran into an issue building the hello world example. Instead I'm getting the following error:
~~~~
$ pwd
/Users/nkpeters/workspace/finch/contrib/hello-finch

$ finch build . -t hello-finch
bash: line 1: cd: /Users/nkpeters/workspace/finch/contrib/hello-finch: No such file or directory
FATA[0000] lstat /Users/nkpeters/Containerfile: no such file or directory
FATA[0000] exit status 1
~~~~

Note that `finch vm init` and `finch run --rm public.ecr.aws/finch/hello-finch` both ran without issue.

**Steps to reproduce**
~~~~
$ git clone git@github.com:runfinch/finch.git
$ cd contrib/hello-finch
$ finch build . -t hello-finch
~~~~

**Expected behavior**
I expect to be able to build the container image using the default finch installation. While I'm happy to debug and figure out how to fix this on my system, my concern is that some users (such as myself) may run into this roadblock which may hinder finch adoption.

**Screenshots or logs**
n/a

**Additional context**
~~~~
$ finch version
Finch version: v0.1.1

$ sw_vers
ProductName:	macOS
ProductVersion:	12.3.1
BuildVersion:	21E258

$ cat ~/.finch/finch.yaml
cpus: 3
memory: 4GiB
~~~~

**Comment by strategicpause** [comment]
Sure.

~~~~
$ echo $HOME
/Users/nkpeters
~~~~

**Comment by strategicpause** [comment]
I just cloned the repository to my home directory and it seems to work now.

~~~~
$ pwd
/Users/nkpeters

$  git clone https://github.com/runfinch/finch.git

$ cd finch/contrib/hello-finch

$ finch  build . -t hello-finch
<expected output>
~~~~

So maybe it is due to the symlink I have?

**Comment by vsiravar** [comment]
Thanks for the experiments @strategicpause . We currently support mounts in `$HOME`. The configuration can be found [here](https://github.com/runfinch/finch/blob/main/finch.yaml#L35). 

```
$ ls -la ~/workspace
lrwxr-xr-x  1 nkpeters  staff  18 May  3  2021 /Users/nkpeters/workspace -> /Volumes/workspace
```
> The symlink doesn't seem relevant, but leaving it for posterity. I'm still seeing the same issue when cloning the repo into /tmp

Since the symlink is to a directory outside of `$HOME` the guest is not able to access the `Containerfile` in the build. Same reason while cloning the repo in `/tmp`. 

We have an enhancement story in our queue to support mounts outside `$HOME`. https://github.com/runfinch/finch/issues/107. 
Hope this helps.

**Comment by strategicpause** [comment]
Closing since this seems like a duplicate of https://github.com/runfinch/finch/issues/107
