### ISSUE TITLE
Misleading error log when starting VM when the Finch config is invalid

### ISSUE THREAD

**Issue by ningziwen** [runfinch/finch#118]
**Describe the bug**
Misleading error log when starting VM when the Finch config is invalid

**Steps to reproduce**
1. Make ~/.finch/finch.yaml an invalid yaml. For example it can just be `invalid yaml`
2. Run `finch vm init`

**Expected behavior**
```
➜  ~ vim ~/.finch/finch.yaml # edit to "invalid yaml"
➜  ~ finch vm init
FATA[0000] failed to load config: failed to unmarshal config file: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `invalid...` into config.Finch
```
It should not mention "using default values", because when the config yaml is invalid, it directly exits with error instead of using default values.
**Screenshots or logs**
```
➜  ~ vim ~/.finch/finch.yaml # edit to "invalid yaml"
➜  ~ finch vm init
FATA[0000] failed to load config: failed to unmarshal config file, using default values: yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `invalid...` into config.Finch
```

**Additional context**

**Comment by pendo324** [comment]
I think the behavior got changed to error out instead of use a default config at some point, but I guess we missed updating the error message. Good catch.
