### ISSUE TITLE
docs: need to mention any required software in CONTRIBUTING.md

### ISSUE THREAD

**Issue by estesp** [runfinch/finch#152]
**Describe the bug**
Running `make` in macOS may use software that isn't installed by default, like the `lz4` utility:
```
mkdir -p /Users/estesp/go/src/github.com/runfinch/finch/finch-core/_output/os
lz4 -dcf /Users/estesp/go/src/github.com/runfinch/finch/finch-core/downloads/os/Fedora-Cloud-Base-37-1.7.aarch64.qcow2 > "/Users/estesp/go/src/github.com/runfinch/finch/finch-core/_output/os/Fedora-Cloud-Base-37-1.7.aarch64.qcow2"
/bin/sh: lz4: command not found
```

**Steps to reproduce**
Run `make` on a default macOS host.

**Expected behavior**
Our contributing guide should let user's know any specific software they should install to get a clean run of the default `Makefile` target.

**Comment by weikequ** [comment]
The CI runs `brew install go lz4 automake autoconf libtool` before building on the host. Are these build deps still up to date @KevinLiAWS? I believe we had them in the original README.md for building the project before it was moved to CONTRIBUTING.md, any reason why it was removed?

**Comment by KevinLiAWS** [comment]
@weikequ I think for local development prerequisite, the instruction needs to include `brew install go lz4 automake autoconf libtool`. I checked the history, and seems it mixed up with the Finch's dependency management but actually these were Finch's build dependencie, so the dependency installation step should be added back.
