### ISSUE TITLE
finch fails with "unrecognized system status"

### ISSUE THREAD

**Issue by otterley** [runfinch/finch#171]
**Describe the bug**
finch can get into a state where, when running any command, it will fail and print

```
FATA[0000] unrecognized system status 
```

**Additional context**
Requested by engineers:

```
❯ LIMA_HOME=/Applications/Finch/lima/data /Applications/Finch/lima/bin/limactl ls
WARN[0000] instance "finch" has errors                   errors="[host agent is running but driver is not]"
NAME     STATUS    SSH                VMTYPE    ARCH       CPUS    MEMORY    DISK      DIR
finch    Broken    127.0.0.1:53899    qemu      aarch64    3       8GiB      100GiB    /Applications/Finch/lima/data/finch
```

**Comment by sam-berning** [comment]
how did you install finch? via homebrew or the github release?

**Comment by otterley** [comment]
Via the GitHub release (DMG file).

**Comment by sam-berning** [comment]
Had you installed via homebrew previously by any chance?

**Comment by otterley** [comment]
No, never.

**Comment by sam-berning** [comment]
Ok, just wanted to rule out any chance that there were two running instances of Finch using the same disk. That's the only context where we've seen this bug before, but it seems like this might be something else.

In any case, https://github.com/runfinch/finch/pull/154 should help prevent this issue from happening. We'll have a release with that PR out soon.

**Comment by sam-berning** [comment]
Just wanted to add a comment here on how to get back into a good state if you run into this issue. The first thing I would try is to manually delete the Lima instance directory, then re-init the finch VM.

```
LIMA_HOME=/Applications/Finch/lima/data/finch /Applications/Finch/lima/bin/limactl remove -f finch
finch vm init
```

If this doesn't fix the issue or if other issues arise with `finch images` or `finch ps`, it's possible that the persistent disk that stores containerd user data is corrupted. In this case, you should also delete the persistent disk. Note that this will cause any saved images or containers to be lost.

```
LIMA_HOME=/Applications/Finch/lima/data/finch /Applications/Finch/lima/bin/limactl remove -f finch
export FINCH_PERSISTENT_DISK=$(readlink /Applications/Finch/lima/data/_disks/finch/datadisk)
LIMA_HOME=/Applications/Finch/lima/data/finch /Applications/Finch/lima/bin/limactl disk delete finch
rm $FINCH_PERSISTENT_DISK
finch vm init
```

**Comment by yamatatsu** [comment]
I get same error when I updated and restarted the Mac OS with finch vm running.

Because I had installed with brew, it fixed by uninstalling and re-installing finch with brew.
