### ISSUE TITLE
Status checks are still required (and waiting) when the 'paths-ignored' is in effect.

### ISSUE THREAD

**Issue by weikequ** [runfinch/finch#18]
**Describe the bug**

When making a PR to edit/add docs, the status checks are still required, even though the workflow is skipped.

**Steps to reproduce**

- Edit docs.
- Create PR.
- See that checks are pending even though the workflow skips them.

**Expected behavior**

- Expect skipped workflows to pass/not be required as status checks.

**Comment by ahsan-z-khan** [comment]
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
