### ISSUE TITLE
finch compose stumbles on restart: on-failure instruction in docker-compose.yml. 

### ISSUE THREAD

**Issue by vsiravar** [runfinch/finch#181]
**Describe the bug**
When `restart: on-failure` instruction is present `docket-compose.yml` file `finch compose up` command throws an error. 

Use docker-compose.yml file from https://github.com/madduci/docker-compiler-explorer. 
**Steps to reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
finch version: 0.0.2
```
% cat docker-compose.yml 
version: "3"

services:
  compiler-explorer:
    build:
      context: ./
      dockerfile: Dockerfile
    image: madduci/docker-compiler-explorer:latest
    restart: on-failure
    container_name: compiler-explorer
    ports:
      - 10240:10240
    networks:
      - ce_network
    stop_grace_period: 1m30s

networks: 
  ce_network:
```

Debug log 
```
% finch compose up --file docker-compose.yml 
INFO[0000] Creating network compose_ce_network          
INFO[0000] Creating network compose_default             
WARN[0000] build.config should be relative path, got "/Users/siravara/vishwas-tests/compose" 
INFO[0000] Ensuring image madduci/docker-compiler-explorer:latest 
INFO[0000] Creating container compiler-explorer         
FATA[0000] error while creating container compiler-explorer: exit status 1 
FATA[0000] exit status 1                                
siravara@bcd074105a94 compose % finch compose up --debug  --file docker-compose.yml
DEBU[0000] Creating limactl command: ARGUMENTS: [shell finch nerdctl compose up --file docker-compose.yml], LIMA_HOME: /Applications/Finch/lima/data 
WARN[0000] build.config should be relative path, got "/Users/siravara/vishwas-tests/compose" 
INFO[0000] Ensuring image madduci/docker-compiler-explorer:latest 
INFO[0000] Creating container compiler-explorer         
FATA[0000] error while creating container compiler-explorer: exit status 1 
FATA[0000] exit status 1  
```
**Expected behavior**
Description of what you expected to happen.
`compose up` should not throw any error. 

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**
Get the same error while running `nerdctl compose up` .

**Comment by monirul** [comment]
`restart: on-failure` is supported in containerd v1.7.0. Prior to v0.6.0, Finch was using containerd 1.6.9 which did not support `restart: on-failure`. Finch v0.6.0 uses containerd v1.7.0. It should work now. I have verified in my local machine with same yml file you provided and it works fine with Finch v0.6.0.
