### ISSUE TITLE
`finch run` command fails, works with `docker run`

### ISSUE THREAD

**Issue by stmcginnis** [runfinch/finch#191]
**Describe the bug**

It is a common pattern to run a container, passing in a bash command to be executing with `docker run`:

```bash
docker run golang:latest bash -c "go version"
go version go1.19.5 linux/arm64
```

This works fine when using Docker, but when using Finch it appears only the first part of the argument gets passed in to the container:

```bash
finch run golang:latest bash -c "go version"
Go is a tool for managing Go source code.

[truncated help output]

Use "go help <topic>" for more information about that topic.

FATA[0000] exit status 2 
```

Any single commands (e.g. `ls`, `pwd`, etc) work fine, but if there is more than a single word, it appears only the first one is actually passed in to be executed.

I am able to get it to work by dropping the `bash -c` part and just providing the command directly:

```bash
finch run golang:latest go version
go version go1.19.5 linux/arm64
```

But there is a lot of documentation out there that follows the failing pattern.

**Steps to reproduce**

Run any command like the above that passes multiple arguments through bash.

**Expected behavior**

All arguments should be passed through and executed by bash in the container.

**Comment by ginglis13** [comment]
I wasn't able to repro this (intel based mac, don't have access to M{1,2})

```
➜  finch git:(main) ✗ finch version
Client:
 Version:	59f372c
 OS/Arch:	linux/amd64
 GitCommit:	59f372cb0875f800015abe989d4eba6b8df92e42
 nerdctl:
  Version:	v1.1.0
  GitCommit:	18944bc70784dfa83010d37054d75487a58ab581
 buildctl:
  Version:	v0.10.6
  GitCommit:	0c9b5aeb269c740650786ba77d882b0259415ec7

Server:
 containerd:
  Version:	v1.6.12
  GitCommit:	a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:	1.1.4
  GitCommit:	v1.1.4-0-g5fd4c4d1
➜  finch git:(main) ✗ finch run golang:latest bash -c "go version"
go version go1.20 linux/amd64
```

And to rule out the specific image being an issue for me as well:

```
➜  finch git:(main) ✗ finch run golang:1.19.5 bash -c "go version"
go version go1.19.5 linux/amd64
```

what is the output of `finch version`?

**Comment by stmcginnis** [comment]
```finch version
Client:
 Version:	v0.3.0
 OS/Arch:	linux/arm64
 GitCommit:	d4a056654991ebb7ef169717c8dcb79105fb53ba
 nerdctl:
  Version:	v1.1.0
  GitCommit:	18944bc70784dfa83010d37054d75487a58ab581
 buildctl:
  Version:	v0.10.6
  GitCommit:	0c9b5aeb269c740650786ba77d882b0259415ec7

Server:
 containerd:
  Version:	v1.6.12
  GitCommit:	a05d175400b1145e5e6a735a6710579d181e7fb0
 runc:
  Version:	1.1.4
  GitCommit:	v1.1.4-0-g5fd4c4d1
```

I've since rebooted my machine which required me to run `finch vm start`. As a sanity check I tried again:

```
finch run golang:latest bash -c "go version"
go version go1.19.5 linux/arm64
```

It appears to be working just fine now. I'm assuming it has to be the reboot that cleared whatever was causing the issue. But whatever the issue was, it also appears it was something in my environment and not something in finch itself. So closing this issue out. Thanks for taking a look!
