### ISSUE TITLE
Support --volumes-from in finch run command

### ISSUE THREAD

**Issue by ningziwen** [runfinch/finch#195]
**What is the problem you're trying to solve?.**
Mount volumes from the specified container(s) in finch run

**Describe the feature you'd like**
```
finch run --volumes-from <container> IMAGE
```

**Additional context**

**Comment by ningziwen** [comment]
Nerdctl issue: https://github.com/containerd/nerdctl/issues/2240

**Comment by vsiravar** [comment]
Resolved in [v0.8.0](https://github.com/runfinch/finch/releases/tag/v0.8.0)
