### ISSUE TITLE
Support rootful containers in finch

### ISSUE THREAD

**Issue by monirul** [runfinch/finch#196]
**What is the problem you're trying to solve?.**
Currently finch runs containers in rootless mode using nerdctl and containerd. This prevents users to set `memlock` in compose yml.

**Describe the feature you'd like**
Finch should support rootful mode.

**Additional context**
Rootless container: A rootless container is a container that could be run without root privileges in the host. 
Rootful container: A rootful container is a container run by root in the host. Since the container is run by root, it has access to all the functionality that root has.

GitHub issue related to memlock:
https://github.com/runfinch/finch/issues/186

**Comment by ningziwen** [comment]
We can either add an config to support rootful mode or switch to rootful mode by default. That needs us to weigh the pros and cons between rootful/rootless.

About the pros of rootful over rootless, other than https://github.com/runfinch/finch/issues/186, https://github.com/runfinch/finch/issues/176 may also be resolved by switching to rootful mode. They need to be further validated in new e2e tests.

**Comment by ningziwen** [comment]
This should also be resolved. https://github.com/runfinch/finch/issues/32
