### ISSUE TITLE
Finch cannot resolve special IP `host-gateway`

### ISSUE THREAD

**Issue by ningziwen** [runfinch/finch#209]
**Describe the bug**
Finch cannot resolve special IP `host-gateway` in `finch run --add-host name:host-gateway IMAGE`

**Steps to reproduce**
```
finch run --add-host name:host-gateway -it public.ecr.aws/amazonlinux/amazonlinux:2 bash
# cat /etc/hosts
...
host-gateway    name
...
```

**Expected behavior**
```
finch run --add-host name:host-gateway -it public.ecr.aws/amazonlinux/amazonlinux:2 bash
# cat /etc/hosts
...
<resolved-ip>    name
...
```

**Screenshots or logs**

**Additional context**
In Docker,
```
docker run --add-host name:host-gateway -it public.ecr.aws/amazonlinux/amazonlinux:2 bash
# cat /etc/hosts
...
192.168.65.2	name
...
```

Can reproduce in nerdctl in Finch VM:
```
nerdctl run --add-host name:host-gateway -it public.ecr.aws/amazonlinux/amazonlinux:2 bash
# cat/etc/hosts
...
host-gateway    name
...
```

**Comment by ningziwen** [comment]
In Finch, to make the feature parity with Docker, the ideal user stories will be:

As a Finch user, if I use `host-gateway` in my `finch run` with configuring `host-gateway-ip` in Finch config, when I try to access host with the alias in container, it will use the ip I configured in Finch config.

```
cat ~/.finch/finch.yaml
...
host-gateway-ip: "192.168.65.2"
...
```

```
finch run --add-host name:host-gateway -it public.ecr.aws/amazonlinux/amazonlinux:2 bash
# cat /etc/hosts
...
192.168.65.2    name
...

## curl name:<port> with a valid port will succeed if 192.168.65.2 is a valid host gateway ip
```

As a Finch user, if I use `host-gateway` in my `finch run` without configuring `host-gateway-ip` in Finch config, my container can still use the IP alias to access host.

```
finch run --add-host name:host-gateway -it public.ecr.aws/amazonlinux/amazonlinux:2 bash
# cat /etc/hosts
...
<default-ip>    name
...
## curl name:<port> with a valid port will succeed
```

**Comment by ningziwen** [comment]
The solution could be split to multiple stages:

At the first stage, we can resolve `host-gateway` to a static IP without being configurable.

Lima has a [static host IP](https://github.com/lima-vm/lima/blob/25b137d4c54a5a251fb7cca4adf1892097e1a6f2/docs/network.md?plain=1#L15) 192.168.5.2 that can be accessed in containers. The value can be retrieved from [code](https://github.com/lima-vm/lima/blob/871a320f609456d609b504feb6cc0a9945ad2d54/pkg/networks/const.go#L7). We can directly resolve host-gateway to it before passing to nerdctl. The value retrieved by Finch will change if Lima changes the value. E2e tests will also be added to validate the ip equals to the value and it can be used to access host.

Making `host-gateway-ip` configurable will come later.

**Comment by ningziwen** [comment]
The first stage is already completed. The next thing to do it to make it configurable in Finch config for feature parity. It requires the nerdctl [change](https://github.com/containerd/nerdctl/pull/1978) to be promoted to Finch.

**Comment by TrungBui59** [comment]
Hi @ningziwen, I want to work on this issue. Can you guide me around it?

**Comment by ningziwen** [comment]
@TrungBui59 

Sure, thanks for the interest! Assigned the issue to you. Feel free to raise any questions directly in the issue. I will be actively monitoring it and helping you.

**Comment by TrungBui59** [comment]
Thank you very much, I am kind of clueless, so can you give me a rough idea on how I should tackle the issue?

**Comment by ningziwen** [comment]
@TrungBui59 Yes. You may follow these steps to start working on this.
1. Understand what is Finch overall, and read the code to understand how Finch uses Cobra as CLI tool and how Finch interacts with Lima and Nerdctl.
2. Understand what is this issue for from the description. (basically for docker feature parity)
3. Read the existing converation and PRs to understand current workaround in Finch, and the existing fix in Nerdctl.
4. Think how to use the existing Nerdctl fix to resolve the issue in Finch and remove the workaround.

**Comment by TrungBui59** [comment]
@ningziwen I see. Thank you

**Comment by TrungBui59** [comment]
@ningziwen 
<img width="932" alt="Screenshot 2023-06-07 at 5 00 17 PM" src="https://github.com/runfinch/finch/assets/70444530/2694bf3a-0c80-40b6-9e49-2b7fb9872fb7">
I thought this is the expected behavior?

**Comment by TrungBui59** [comment]
@ningziwen Just to make sure my solution is acceptable. I will add a new field called host-gateway-ip on the finch.yaml. I will then parse by changing the pkg/config.go file and then get the data and pass to the SlirpGateway. Then Im gonna use it when user specify the ip

**Comment by ningziwen** [comment]
My understanding is [SlirpGateway](https://github.com/lima-vm/lima/blob/9d29da396c164fea261bc547b4537d470aa3a824/pkg/networks/const.go#L7) IP is a constant value in Lima, which is not designed to be configure.

This nerdctl change introduced a host-gateway-ip field in nerdctl config, which is designed to be configurable. https://github.com/containerd/nerdctl/pull/1978/files

So my suggestion is if host-gateway-ip exists in finch config, pass it to host-gateway-ip in nerdctl config. Otherwise, pass SlirpGatewayIP to host-gateway-ip in nerdctl config.

Let me know if you have different thoughts.

**Comment by TrungBui59** [comment]
@ningziwen  I have some issue with the tests. Unit tests keep giving me race condition on file I dont even touch. and e2e test is output something that I dont quite understand

e2e:
<img width="1467" alt="Screenshot 2023-06-12 at 5 00 07 PM" src="https://github.com/runfinch/finch/assets/70444530/342e486e-fa6a-4aec-be45-8da6cc5b81c2">

unittest:
<img width="1470" alt="Screenshot 2023-06-12 at 5 02 49 PM" src="https://github.com/runfinch/finch/assets/70444530/2c4da229-6abe-475f-87aa-148f7e056f6b">

**Comment by TrungBui59** [comment]
@ningziwen so for the e2e test, what does that error mean?

**Comment by TrungBui59** [comment]
@ningziwen  This is all it shown me. It even shows this before I add some code change
<img width="723" alt="Screenshot 2023-06-12 at 5 34 45 PM" src="https://github.com/runfinch/finch/assets/70444530/0b6704e7-8017-45b0-8e6c-847306904008">

**Comment by ningziwen** [comment]
@TrungBui59 For e2e tests, most of the Finch e2e tests are in common-tests repo. And here is the failing test scenario from your log. https://github.com/runfinch/common-tests/blob/6c7275007bf34fb6ddecc4013c16f1d79ff6d1d0/tests/run.go#L335
Finch e2e tests use a framework called [Ginkgo](https://onsi.github.io/ginkgo/).

The tests are failing because your change broke them. You also need to scroll up to find the failed scenario and get more useful logs from there.

**Comment by TrungBui59** [comment]
@ningziwen I have finished the task, but there is one question I want to make sure. If the user update the host_gateway_ip in the finch config file, do we only allow to update it when they init the VM or they can update when they start the VM?

**Comment by ningziwen** [comment]
@TrungBui59 
We think we should try to allow them update when they start (restart) the VM. 
Why close the PR?

**Comment by TrungBui59** [comment]
@ningziwen Got it. For the PR, it was an accident, I type a command and somehow it closed the PR

**Comment by TrungBui59** [comment]
@ningziwen sorry for not really finishing earlier, I was quite busy with my work. Is this issue still open? If it is, I will be able to finish this by the couple next days

**Comment by ningziwen** [comment]
> @ningziwen sorry for not really finishing earlier, I was quite busy with my work. Is this issue still open? If it is, I will be able to finish this by the couple next days

@TrungBui59 No worries. It is still open. Feel free to complete it.

**Comment by Shubhranshu153** [comment]
Retested this, seems this has been implemented:
```
192.168.5.2     name
```
