### ISSUE TITLE
mounting using /Volumes path on mac fails

### ISSUE THREAD

**Issue by thirtytwobits** [runfinch/finch#220]
**Describe the bug**
My workflow regularly uses a docker command like this:

```
docker run --rm -it -v  /Volumes/workspace/github/thirytwobits/nunavut:/repo ghcr.io/opencyphal/toolshed:ts20.4.1
```

Replacing `docker` with `finch` fails with "No such file or directory". Using any other path that is not on my `/Volumes/workspace` volume succeeds.

**Steps to reproduce**
Create another partition on a mac and mount. (we'll call this volume `/Volumes/workspace` for these steps)

```
finch run --rm -it -v  /Volumes/workspace/github/thirytwobits/nunavut:/repo ghcr.io/opencyphal/toolshed:ts20.4.1
```

**Expected behavior**
an interactive shell is started and doing `cd /repo; ls -lah` would show the contents of the local `/Volumes/workspace/github/thirytwobits/nunavut` folder.

**Screenshots or logs**

```
finch --debug run --rm -it -v  /Volumes/workspace/github/thirytwobits/nunavut:/repo ghcr.io/opencyphal/toolshed:ts20.4.1
DEBU[0000] Creating limactl command: ARGUMENTS: [shell finch nerdctl run --rm -it -v /Volumes/workspace/github/thirytwobits/nunavut:/repo ghcr.io/opencyphal/toolshed:ts20.4.1], LIMA_HOME: /Applications/Finch/lima/data
bash: line 1: cd: /Volume /workspace/github/thirtytwobits/nunavut: No such file or directory
FATA[0000] no such file or directory
FATA[0000] exit status 1
```

**Additional context**

Ventura 13.2, 2.4 GHz 8-Core Intel Core i9

**Comment by ningziwen** [comment]
The non-home directories are not mounted by default. You can follow the [docs](https://github.com/runfinch/finch#configuration) to modify Finch config to mount additional directories.

**Comment by thirtytwobits** [comment]
tried that but it doesn't seem to help. I stopped and started the vm after updating my yaml. Is there something else I need to do?

**Comment by thirtytwobits** [comment]
nevermind. It did work. My bad. Thanks!

**Comment by thirtytwobits** [comment]
I suppose this could move to an enhancement to provide an error message pointing the user to the docs about adding these paths?

**Comment by thirtytwobits** [comment]
Okay, well. I'll close this as RTFM then.

**Comment by ningziwen** [comment]
> I suppose this could move to an enhancement to provide an error message pointing the user to the docs about adding these paths?

Yeah that's a good idea. We have not added doc link to error message yet so the feasibility needs to be evaluated.
