### ISSUE TITLE
Support stopped containers as source/target of `finch cp`

### ISSUE THREAD

**Issue by RomainMuller** [runfinch/finch#243]
**What is the problem you're trying to solve?.**
Copying files from/into stopped containers with `finch cp`.

Example of a failure we get currently:
```
Bundling asset integ-lambda-python-function-dockercopy/my_handler/Code/Stage...
assetInput34207097c759333cd69be379
assetOutput34207097c759333cd69be379
time="2023-02-27T15:36:52Z" level=warning msg="failed to inspect NetNS" error="failed to Statfs \"/proc/77113/ns/net\": no such file or directory" id=e6d7abdfc6204bf162f0f2e2cd15c72551a69e6b90855276bceccff36fb462f1
time="2023-02-27T15:36:52Z" level=fatal msg="expected container status running, got stopped"
time="2023-02-27T16:36:52+01:00" level=fatal msg="exit status 1"
/Users/rmuller/Development/aws/aws-cdk/packages/aws-cdk-lib/core/lib/asset-staging.js:2

Error: Failed to bundle asset integ-lambda-python-function-dockercopy/my_handler/Code/Stage, bundle output is located at /Users/rmuller/Development/aws/aws-cdk/packages/individual-packages/aws-lambda-python/test/cdk-integ.out.integ.function.dockercopy.js.snapshot/asset.7ff10f587d4a6ca78a132c2ac7eecaf8d4611d262e2f3b006cfdff011ef38519-error: Error: finch exited with status 1
--> Command: finch cp "/Users/rmuller/Development/aws/aws-cdk/packages/individual-packages/aws-lambda-python/test/lambda-handler-dockercopy/." "copyContainer34207097c759333cd69be379:/asset-input"
```

In the case above, `copyContainer34207097c759333cd69be379` is stopped at the time the `finch cp` command was attempted.

**Describe the feature you'd like**
In essence, we'd need parity with [`docker cp`](https://docs.docker.com/engine/reference/commandline/cp/#description) on this front, where documentation states the following (and behavior tracks, although -- emphasis is mine):

> The `docker cp` utility copies the contents of `SRC_PATH` to the `DEST_PATH`. You can copy from the container’s file system to the local machine or the reverse, from the local filesystem to the container. If `-` is specified for either the `SRC_PATH` or `DEST_PATH`, you can also stream a tar archive from `STDIN` or to `STDOUT`. **The `CONTAINER` can be a running or stopped container.** The `SRC_PATH` or `DEST_PATH` can be a file or directory.

**Additional context**
This currently breaks some asset bundling code paths from working in AWS CDK when using `finch`, which is not ideal.

**Comment by vsiravar** [comment]
Investigating upstream issue: https://github.com/containerd/nerdctl/issues/1058.

**Comment by vsiravar** [comment]
Fixed upstream: https://github.com/containerd/nerdctl/pull/2355
