### ISSUE TITLE
Time synchronization

### ISSUE THREAD

**Issue by sectoramen** [runfinch/finch#248]
**Describe the bug**
After leaving the finch vm running on my laptop for an extended period of time, i.e. days, containers' time are skewed.

**Steps to reproduce**
```
finch run image date
Tue Feb 28 20:43:30 UTC 2023
finch vm stop 
finch vm start
finch run image date                                                                                   
Tue Feb 28 21:16:47 UTC 2023 
```

**Expected behavior**
The finch vm should sync its time

**Comment by Shubhranshu153** [comment]
```
Open: ~/.finch/finch.yaml
Set:
vmType: vz
Then restart finch:
finch vm stop && finch vm start 
```
moving to vz vm resolves the skew.
