### ISSUE TITLE
This name is already in use...

### ISSUE THREAD

**Issue by grimmy** [runfinch/finch#26]
**Describe the bug**

You used the name of a product that's been around since 2007. 

**Steps to reproduce**
Look at the name of the repository

**Expected behavior**
Not to have a someone add confusion to the market place by reusing an existing products name.

**Screenshots or logs**

```
$ apt-cache search ^finch
finch - text-based multi-protocol instant messaging client
finch-dev - text-based multi-protocol instant messaging client - development
finch-dbgsym - debug symbols for finch
```

**Additional context**
https://en.wikipedia.org/wiki/Finch_(software)
https://developer.pidgin.im/wiki/Using%20Finch
https://packages.debian.org/unstable/finch
and many many more...

**Comment by jlbutler** [comment]
Hi @grimmy 👋 

The project team are aware of this Finch (I used it myself back in the day), and also the Finagle project has a Scala library named Finch. I'm sure there are others.

We really loved this name for the project, and thought about collision and confusion more than if the name had ever been in use before. We hope that the use case is different enough that it shouldn't be a problem.

Let us know if you disagree, thanks!

**Comment by rlaager** [comment]
Debian has a policy of not allowing duplicated command names. So if this finch were to be packaged for Debian, its name would have to be different. That would be a pain for your users.

**Comment by jlbutler** [comment]
Thanks, good callout. We don’t anticipate a Linux-native `finch` binary as part of this project, so Linux distro packaging shouldn’t be a worry.

**Comment by jlbutler** [comment]
Without further discussion I'm going to close this one out. Open to more discussion any time, but for now will close. Thanks all.
