### ISSUE TITLE
Flacky e2e test in Compose down command

### ISSUE THREAD

**Issue by KevinLiAWS** [runfinch/finch#261]
**Describe the bug**
In the e2e test, we saw high possiblility failed tests:

[FAIL] Finch Container Development E2E Tests Compose down command [It] should stop compose services and delete volumes by specifying -v flag

It takes extra efforts to re-run for 30 mins and still has chance to fail.
Although other tests can also be flacky, we saw this test fail ~50% of the runs.

**Steps to reproduce**
It happens randomly during merge validation or installer test.

**Expected behavior**
The test should be more stable.

**Comment by AnqiPang** [comment]
Some E2E test failures for this test:
https://github.com/runfinch/finch/actions/runs/4320447573/jobs/7540706536
https://github.com/runfinch/finch/actions/runs/4309575538/jobs/7517124406

**Comment by monirul** [comment]
It seems the e2e test failed for valid reason. It seems the `compose down` command could not delete the volume as it suppose to do. 


  time="2023-03-02T01:18:42Z" level=warning msg="error while executing [/usr/local/bin/nerdctl volume rm -f finch-compose2256652280_compose_data_volume]: \"time=\\\"2023-03-02T01:18:42Z\\\" `level=fatal msg=\\\"volume \\\\\\\"finch-compose2256652280_compose_data_volume\\\\\\\" is in use\\\"\\n\": exit status 1"`
  6f05dc49b2bb

If we want to exclude this error from the e2e test then we might need to modify the e2e test.

**Comment by KevinLiAWS** [comment]
Hi @monirul, do you mean it is an expected and valid case that the compose down can't delete the volume sometimes? Could adding some delay before the deletion, retry or force release the hold of the volume help fix this case?

**Comment by KevinLiAWS** [comment]
The compose tests are fixed in 0.6.0
