### ISSUE TITLE
Can't start postgres and some other images

### ISSUE THREAD

**Issue by aleksey925** [runfinch/finch#284]
**Describe the bug**
When I try to run postgres via compose I get an error.

```
finch compose up
INFO[0000] Creating network finch-test_default          
INFO[0000] Ensuring image postgres:14                   
INFO[0000] Creating container finch-test_db_1           
FATA[0000] error while creating container finch-test_db_1: exit status 1 
FATA[0000] exit status 1  
```

**Steps to reproduce**
1. Create docker-compose.yml

```
services:
  db:
    image: postgres:14
    restart: on-failure:10
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
    ports:
      - 5432:5432

```

2.  finch compose up

**Expected behavior**
Postgres successfully runned.

**Screenshots or logs**
```
finch compose up
INFO[0000] Creating network finch-test_default          
INFO[0000] Ensuring image postgres:14                   
INFO[0000] Creating container finch-test_db_1           
FATA[0000] error while creating container finch-test_db_1: exit status 1 
FATA[0000] exit status 1  
```

**Additional context**
finch version v0.4.1

**Comment by ahsan-z-khan** [comment]
I have also reproduced the issue. Asking @monirul  to look into it further:

`INFO[0012] Creating container finch_db_1
FATA[0012] error while creating container finch_db_1: exit status 1
FATA[0013] exit status 1`

**Comment by monirul** [comment]
The error occurred due to `restart: on-failure:10` in compose yml file. Currently, finch uses containerd 1.6.19 which does not support `restart: on-failure:10`.
Work around: remove the  `restart: on-failure:10` from the compose yml file.
e.g.
```
services:
  db:
    image: postgres:14
    restart: on-failure:10
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=test
    ports:
      - 5432:5432
```
