### ISSUE TITLE
Freqtrade docker image error

### ISSUE THREAD

**Issue by rajeevjaiiswal** [runfinch/finch#310]
**Describe the bug**
Getting error while building image for freqtrade(https://www.freqtrade.io/en/stable/). Same is working with docker desktop for windows.
BUILD -> finch build --platform linux/amd64  ...
error: failed to solve: process "/bin/sh -c cd /tmp && /tmp/install_ta-lib.sh && rm -r /tmp/*ta-lib*" did not complete successfully: exit code: 1
FATA[0231] no image was built                           
FATA[0232] exit status 1

**Steps to reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
Install freqtrade(https://www.freqtrade.io/en/stable/) using script on Mac and build using -> finch build --platform linux/amd64  

**Expected behavior**
Description of what you expected to happen.
Build image successfuly as docker works witthout any issue.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

**Comment by ginglis13** [comment]
Hi @rajeevjaiiswal, I was able to build the project with Finch.

```
$ git clone git@github.com:freqtrade/freqtrade.git && cd freqtrade
$ finch build --platform linux/amd64 -f Dockerfile .
```

I'm going to go ahead an close this. Feel free to reopen with additional details if you're facing this or a similar issue.
