### ISSUE TITLE
The logo isn't visible in the README with the dark theme

### ISSUE THREAD

**Issue by alexellis** [runfinch/finch#34]
**Describe the bug**
Briefly describe the problem you are having.

The logo isn't visible in the README with the dark theme

**Steps to reproduce**
A clear, step-by-step set of instructions to reproduce the bug.

Enable dark theme on MacOS, view the readme with Safari

**Expected behavior**
Description of what you expected to happen.

See the logo

Initially, I thought there was no readme until I scrolled down.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

<img width="1426" alt="Screenshot 2022-11-23 at 08 46 13" src="https://user-images.githubusercontent.com/6358735/203504158-733c2524-84dc-4c9f-930a-4d955f1ec926.png">

**Comment by weikequ** [comment]
I believe @chris-short is looking at this in https://github.com/runfinch/finch/pull/25.

**Comment by chris-short** [comment]
Correct
