### ISSUE TITLE
Add benchmarking in Finch

### ISSUE THREAD

**Issue by ningziwen** [runfinch/finch#345]
**What is the problem you're trying to solve?.**
Report the key metric benchmarking in CI and persistent diagram.

**Describe the feature you'd like**
`go test -bench .` could be the interface to start from.
[Continuous benchmark Github action](https://github.com/marketplace/actions/continuous-benchmark) may be integrated to report in CI and persistent diagram.

**Additional context**

**Comment by ningziwen** [comment]
[PR](https://github.com/runfinch/finch/pull/344) to add barebone benchmarking for `vm init` and `vm start` only.

**Comment by estesp** [comment]
Should this issue be closed now @ningziwen ?

**Comment by ningziwen** [comment]
Closing the issue as the basic benchmarking result is already in Finch. https://runfinch.github.io/finch/dev/bench/

Code: https://github.com/runfinch/finch/tree/gh-pages/dev/bench

Further benchmarking enhancements will be tracked in separated issues.
