### ISSUE TITLE
[Feature request] Install finch via homebrew

### ISSUE THREAD

**Issue by e-minguez** [runfinch/finch#37]
**What is the problem you're trying to solve?.**

Installing finch by downloading the binary is ok, but integrating it with homebrew for upgrades would be even better.

**Describe the feature you'd like**

Homebrew is the _de facto_ standard to install software on OSX, so making it available to install as `brew install finch` would make easier for folks to install and update it.

**Additional context**

**Comment by webframp** [comment]
Considering there's already an aws tap: https://github.com/aws/homebrew-tap maybe it could go there?

**Comment by webframp** [comment]
Added a recipe top my personal tap for now, feel free to use it

**Comment by KevinLiAWS** [comment]
Thanks a lot @chenrui333 and @miccal for adding finch into homebrew cask!
Now finch can be installed via homebrew. One thing to call out is that we are working on uninstall to do a deeper clean up, for now you install via homebrew and would like to uninstall and clean up, the workaround is manually delete:
/opt/finch/
/private/var/run/finch-lima
/private/etc/sudoers.d/finch-lima

**Comment by chenrui333** [comment]
> One thing to call out is that we are working on uninstall to do a deeper clean up, for now if you install via homebrew and would like to uninstall and clean up, the workaround is manually delete:
> /opt/finch/
> /private/var/run/finch-lima
> /private/etc/sudoers.d/finch-lima

let me update the zap step
