### ISSUE TITLE
finch compose logs forces runtime dependencies between services

### ISSUE THREAD

**Issue by wolanlu** [runfinch/finch#386]
**Describe the bug**
This bug can be related to https://github.com/runfinch/finch/issues/385. The behaviour of `finch compose logs` is similar. It should show only logs of specified service but it also **does** show all depends_on services logs as well.

**Steps to reproduce**
1. One need a docker-compose file defining more then one service e.g.: 
<img width="496" alt="Screenshot 2023-04-28 13-55-44" src="https://user-images.githubusercontent.com/107101734/235141166-e45fd825-0044-469a-ad98-a3deda82cc9d.png">

2. `finch compose logs app`

**Expected behavior**
Shows only logs of **app** service

**Screenshots or logs**
This screen show that also logs of **db** service which **app** depends_on are shown:
<img width="644" alt="Screenshot 2023-04-28 14-06-12" src="https://user-images.githubusercontent.com/101870655/235143147-07f05302-bb32-4643-98aa-c2b751a5b888.png">

**Additional context**

_To help debug the issue as quickly as possible, we recommend generating a support bundle with `finch support-bundle-generate` and attaching it to this issue. This packages all Finch-related configs and logs into one file._

**Comment by ningziwen** [comment]
Validated Docker only prints logs of the service without dependencies in `compose logs`.
```
docker compose logs svc1
finch-svc1-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
finch-svc1-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
finch-svc1-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
finch-svc1-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
finch-svc1-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
finch-svc1-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
finch-svc1-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
finch-svc1-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
```

**Comment by ningziwen** [comment]
Validated fixed.

```
finch compose logs svc1
svc1-1 |/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
svc1-1 |/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
svc1-1 |/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
svc1-1 |10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
svc1-1 |10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
svc1-1 |/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
svc1-1 |/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
svc1-1 |/docker-entrypoint.sh: Configuration complete; ready for start up
```
