### ISSUE TITLE
Uninstalling Finch does not clean up the container data disk

### ISSUE THREAD

**Issue by ollypom** [runfinch/finch#457]
**Describe the bug**
When a user uninstalls Finch (either with `sudo bash /Applications/Finch/uninstall.sh` or `brew uninstall finch`), the container data disk is not cleaned up as it lives in the `~/.finch` directory. 

Users could have GBs of data in this container data disks that is now, unknowing to the user, orphaned. We should clean it up allowing a user to reclaim the space.

**Comment by haytok** [comment]
Hi, @KevinLiAWS 

If no one is working on this issue, could you please assign me ?
I would like to work on this issue and add the feature to clean up `~/.finch/.disks` in uninstalling finch.

**Comment by Shubhranshu153** [comment]
Fix has been merged
