### ISSUE TITLE
Project logo needs to account for different backgrounds

### ISSUE THREAD

**Issue by stmcginnis** [runfinch/finch#46]
**Describe the bug**

The current logo is black on a transparent background. This assumes the logo will only ever be seen with a white or light background. This is a poor assumption.

**Steps to reproduce**

Enable dark mode and view the rendered GitHub README

**Expected behavior**

It would be better to either have a solid background, or have tracing around the black elements of the logo to make sure they are visible when put over different colored backgrounds.

**Screenshots or logs**

![image](https://user-images.githubusercontent.com/3922475/203636401-061a9535-52a6-486a-95b6-fa455c04c7a7.png)

**Comment by weikequ** [comment]
Yeah, agreed! See https://github.com/runfinch/finch/issues/34

**Comment by stmcginnis** [comment]
How did I miss that! Thanks for the pointer.
