### ISSUE TITLE
Flaky test: containers still exist after compose down

### ISSUE THREAD

**Issue by ningziwen** [runfinch/finch#460]
**Describe the bug**
[FAIL] Finch Container Development E2E Tests Compose down command [It] should stop compose services and delete volumes by specifying -v flag
https://github.com/runfinch/finch/actions/runs/5354698993/jobs/9712336180

**Steps to reproduce**
Flaky test is hard to reproduce.

**Expected behavior**
The test should succeed.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

_To help debug the issue as quickly as possible, we recommend generating a support bundle with `finch support-bundle generate` and attaching it to this issue. This packages all Finch-related configs and logs into one file._

**Comment by ningziwen** [comment]
```
• [FAILED] [4.510 seconds]
Finch Container Development E2E Tests Compose down command [It] should stop compose services and delete volumes by specifying -v flag
/Users/ec2-user/go/pkg/mod/github.com/runfinch/common-tests@v0.7.0/tests/compose_down.go:45

  [FAILED] Expected
      <[]uint8 | len:13, cap:13>: [51, 55, 54, 49, 50, 100, 48, 48, 100, 48, 97, 53, 10]
  to be empty
  In [It] at: /Users/ec2-user/go/pkg/mod/github.com/runfinch/common-tests@v0.7.0/tests/tests.go:137 @ 06/23/23 09:24:20.648
```

Based on the log, the containers still exist after compose down command returns back. Looking into the nerdctl [code](https://github.com/containerd/nerdctl/blob/242c6b92bcb6a6d1522104dc7206d2886b7e9cc8/pkg/composer/rm.go#L89), the actual container removing is under go routine, which is asynchronous.

So adding retry in tests should address this.

**Comment by Shubhranshu153** [comment]
Fix has been merged
