### ISSUE TITLE
Finch benchmarks show incorrect label for VM init charts.

### ISSUE THREAD

**Issue by austinvazquez** [runfinch/finch#488]
**Describe the bug**
Inspecting the data on VM init benchmarks show incorrect label on the data. The chart label is `s/op` but the data is still showing `ns/op` even after https://github.com/runfinch/finch/pull/470

**Steps to reproduce**
Hover a VM init benchmark datapoint e.g. https://runfinch.github.io/finch/dev/bench/macOS/12/arm64/index.html

**Expected behavior**
Expected label to be `s/op`

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**
The data seems converted correctly, so probably just a missed label.

_To help debug the issue as quickly as possible, we recommend generating a support bundle with `finch support-bundle generate` and attaching it to this issue. This packages all Finch-related configs and logs into one file._

**Comment by ningziwen** [comment]
Closed as completed.
