### ISSUE TITLE
Support Finch on Windows

### ISSUE THREAD

**Issue by pendo324** [runfinch/finch#492]
**What is the problem you're trying to solve?.**
Windows users should be able to use Finch. I provided some thoughts on how this could be implemented below, but I'm happy to take comments on this issue directly to influence the design before the implementation is finalized.

**Describe the feature you'd like**
A user experience consistent with Finch on macOS, but for container developers that prefer Windows.

**Additional context**
Similar to #377, but for Windows instead of Linux.

Regarding implementation details, I think the ideal way to proceed is to add support for Windows to our dependencies, namely, Lima. This way, most of the work could be reused by other projects that depend on Lima, and the Finch changes would be minimal, and mostly around packaging and distribution.

Based on my research so far, it seems like WSL2 is the best way to implement this in Lima, via a new VM driver (similar to how there's a QEMU driver and a VZ driver in Lima already). WSL2 seems to be a long-term, Microsoft supported feature of Windows, so we don't have to worry about maintaining the Virtualization stack ourselves. However, this also means that we can't really contribute to bug fixes and adding new features to WSL2. Technically, there are two main points against WSL2: disk I/O speed and hardware support.

Disk I/O performance is limited because of the way files are shared between the main Windows filesystem and the Linux filesystem (plan 9 fs server). It's likely that the existing performance is good enough for most user's use cases though. It's possible that Microsoft addresses this concern over time.

Hardware support for WSL2 is limited to CPUs/Motherboards that have VT-x/VT-d / AMD-V / SVM support. Other options, like HyperV also have these hardware limitations. QEMU technically does not have this limitation as it can fall back to software virtualization, but this is not really practical for any sort of "good" user experience. Besides the hardware support, certain Windows features need to be enabled, but this can be automated by Finch or Lima directly and is not as much of an issue (will just require more careful error handling / messaging).

WSL2 VMs initialize from root filesystem archives instead of disk images (qcow2/img/iso), so we will also need to adjust our OS building process to support WSL2, and will need to adjust Lima to support these new root filesystem archives when using the WSL2 driver.

**Comment by estesp** [comment]
Can we close this issue?

**Comment by pendo324** [comment]
Closed by #778, and installer available in [v1.1.1](https://github.com/runfinch/finch/releases/tag/v1.1.1)
