### ISSUE TITLE
[Errno 12] OOM issue when composing finch

### ISSUE THREAD

**Issue by aoshuang17** [runfinch/finch#512]
**Describe the bug**
I started to see this timeout error on multiple resources when composing finch, and it never completes.
```
 => => transferring context: 330.90MB                                                                                                                                                                              105.0s
 => [2/4] RUN yum update -y &&     yum install -y gcc gcc-c++ kernel-devel make python                                                                                                                             104.9s
 => => # https://rpm.nodesource.com/pub_14.x/el/7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://rpm.nodesource.com/pub_14.x/el/7/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 5000 millisecond
 => => # s')
 => => # Trying other mirror.
 => => # https://rpm.nodesource.com/pub_14.x/el/7/x86_64/repodata/repomd.xml: [Errno 12] Timeout on https://rpm.nodesource.com/pub_14.x/el/7/x86_64/repodata/repomd.xml: (28, 'Resolving timed out after 5000 millisecond
 => => # s')
 => => # Trying other mirror. 
```
[Errno 12] looks like a [out of memory issue](https://zchee.github.io/golang-wiki/LinuxKernelSignalVectorBug/).. 

I’ve tried to the following steps but the issue persists
* `finch image prune --all`
* allocated 16GB memory(memory available on the system) in `~/.finch/finch_yaml`,
* `finch vm stop && finch vm start`

**Steps to reproduce**
In my mac run the following commands
```
finch compose -f docker-compose.yml up --build -d
```

**Expected behavior**
The command should complete successfully and containers created

**Screenshots or logs**
See description

**Additional context**
N/A

_To help debug the issue as quickly as possible, we recommend generating a support bundle with `finch support-bundle generate` and attaching it to this issue. This packages all Finch-related configs and logs into one file._

**Comment by aoshuang17** [comment]
I tried to stop and restart vm or recreated vm they did not help me yesterday. but somehow the compose command ran successfully just now after a stop and restart vm. Apart from that, I did nothing special except putting laptop to sleep

**Comment by kmturley** [comment]
Had the same issue. To fix I had to:
- Restart my laptop
- Run `finch vm stop` and then `finch vm start`

Note: I also changed any references:
`public.ecr.aws` to `gallery.ecr.aws`
