### ISSUE TITLE
Not able to pull image from finch.

### ISSUE THREAD

**Issue by spbhati** [runfinch/finch#534]
**Describe the bug**
I have created a image on finch but not able to download that image in local.

**Steps to reproduce**
created image using below command
finch build . -t hello-finch

now when we are trying to download we are getting below error.
"pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed" [host=registry-1.docker.io](http://host%3Dregistry-1.docker.io/)"

**Comment by spbhati** [comment]
command I am not aware about to pull image in local system. I was trying as per help command.
lima nerdctl pull image ipfs://public.ecr.aws/redshiftconnect:latest

in mac lima have inbuilt nerdctl system. so I installed lima on mac and tried to use this.

**Comment by sbuckfelder** [comment]
Hello - this looks like there is an authorization issue.  For ECR public please look at the following docs from AWS:
 https://docs.aws.amazon.com/AmazonECR/latest/public/public-registries.html#public-registry-auth

I am looking at reproducing on my side.

**Comment by spbhati** [comment]
Hi @sbuckfelder 

Thanks for the update. I will check this document for access. Meanwhile can you confirm on command that I am using to pull image. Is this correct, if not what is the correct way to download it on local machine.

**Comment by sbuckfelder** [comment]
Would you be able to share the Dockerfile that you were building with `finch build . -t hello-finch`?  I'm guessing there is a FROM statement that is referencing Dockerhub.

**Comment by spbhati** [comment]
This is the code related to my docker file.

FROM python:latest 

ADD requirements.txt /
RUN pip install -r requirements.txt
ADD RedshiftTest.py / 
CMD [ "python","./RedshiftTest.py" ]

**Comment by sbuckfelder** [comment]
Can you try `finch pull python:latest`?  Does that work?

**Comment by spbhati** [comment]
I ran that command and it processed on terminal successfully with downloading and then done status
 but not getting any image or file in local path.

<img width="999" alt="Screenshot 2023-08-17 at 3 02 38 PM" src="https://github.com/runfinch/finch/assets/142379118/315c4e6b-aa1a-479f-a8e5-96083980a12f">

**Comment by sbuckfelder** [comment]
Ok - so what that command did was pull down the image from docker hub into the virtual machine.  Could you elaborate what you mean by "the image or file in local path"?  How are you checking that?

Also, I'd expect `finch build . -t hello-finch` to work now.  Does it?

**Comment by sbuckfelder** [comment]
Spoke directly with @spbhati.  Confirmed build worked and the issue is stemming from getting proper aws credentials / permissions.  We are going to keep the issue open until he is able to push to the remote repo.

**Comment by sbuckfelder** [comment]
Spoke with @spbhati, he was able to get it working once he was logging into his aws account.
