### ISSUE TITLE
`make clean` retains downloads in `deps/finch-core`

### ISSUE THREAD

**Issue by ginglis13** [runfinch/finch#537]
**Describe the bug**
`make clean` does not clean submodule downloads in `deps/finch-core/downloads`

**Steps to reproduce**
```sh
make

ls deps/finch-core/downloads/os

make clean

ls deps/finch-core/downloads/os
```

**Expected behavior**
I would expect `make clean` to remove the downloaded OSs as each are > 500mb, or there to at least be a rule such as `make deps-clean` to remove these. Alternatively, if the idea behind *not* cleaning these is so that they don't need to keep being redownloaded, the rule could have some regex and/or could be modified by the [`Sync Submodules and Dependencies`](https://github.com/runfinch/finch/actions/workflows/sync-submodules-and-deps.yaml) action to only delete OS/rootfs that don't match the latest available.

**Comment by haytok** [comment]
Hi, @ginglis13 
I would like to work on this issue, so could you please assign me ?
