### ISSUE TITLE
Resolve ShellCheck lint warnings

### ISSUE THREAD

**Issue by austinvazquez** [runfinch/finch#550]
**What is the problem you're trying to solve?.**
https://github.com/runfinch/finch/pull/458 added ShellCheck to Finch CI for linting Finch shell scripts. The step is currently non-critical due to some lingering non-trivial lint warnings.

**Describe the feature you'd like**
It would be nice to resolve the remaining warnings and make the CI step critical.

**Additional context**
N/A

**Comment by RiverPhillips** [comment]
I'd like to look into this

**Comment by mharwani** [comment]
Issue is fixed. Closing.
