### ISSUE TITLE
Finch Icon doesn't show up on GitHub iPhone App

### ISSUE THREAD

**Issue by ChandruShetty** [runfinch/finch#56]
**Describe the bug**
Finch logo is blank in the GitHub App finch repository.

**Steps to reproduce**
1. Open GitHub app on your iPhone.
2. Go to finch repository.
3. Check the read me section.
4. Finch logo/icon is blank. 

**Expected behavior**
Finch icon is displayed.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**[![image](https://user-images.githubusercontent.com/8681376/204111075-8d64c890-90f2-49c8-ab5c-55093a5e2c27.jpeg)]()Additional context**

**Comment by weikequ** [comment]
Seems like a standing issue. See:
- https://github.com/github/markup/issues/556
- https://github.com/isaacs/github/issues/316

**Comment by ChandruShetty** [comment]
Thanks for taking care of this. Icon now shows up in the GitHub App.
