### ISSUE TITLE
Run the SOCI snapshotter with systemd

### ISSUE THREAD

**Issue by ollypom** [runfinch/finch#660]
**What is the problem you're trying to solve?.**
Today we are running the SOCI snapshotter as a [background process](https://github.com/runfinch/finch/blob/c199b6701824ab32d1b00676b6f7f072fa4f8c01/pkg/config/lima_config_applier.go#L41). Could we switch to running the SOCI snapshotter as a systemd service? Among many other benefits, it would help centralize soci snapshotter logs into journald. The SOCI snapshotter project already provides an [example systemd file](https://raw.githubusercontent.com/awslabs/soci-snapshotter/main/soci-snapshotter.service).

We also are already running the stargz snapshotter with systemd in Finch (Another outstanding question here is should we be? considering we don't expose stargz in the [Finch configuration file](https://github.com/runfinch/finch/blob/c199b6701824ab32d1b00676b6f7f072fa4f8c01/pkg/config/lima_config_applier.go#L126)).

```bash
$ sudo systemctl status stargz-snapshotter
● stargz-snapshotter.service - stargz snapshotter
     Loaded: loaded (/usr/local/lib/systemd/system/stargz-snapshotter.service; enabled; preset: disabled)
    Drop-In: /usr/lib/systemd/system/service.d
             └─10-timeout-abort.conf
     Active: active (running) since Thu 2023-10-26 10:30:09 UTC; 16min ago
```

**Describe the feature you'd like**
Could we switch to running the SOCI snapshotter as a systemd service?

**Additional context**

**Comment by ginglis13** [comment]
@ollypom starting soci as a normal process on boot proved to be an issue with the Windows implementation of Finch, so we opted to pivot to starting soci as a systemd service as part of that effort. 

See https://github.com/runfinch/finch/blob/998989a5ccf8740177040f39bcf28c9763c549a6/pkg/config/lima_config_applier.go#L39-L46

which is included in #649 

We can opt to either port that commit over to `main` ASAP, or wait for the release of Finch that includes Windows support.
