### ISSUE TITLE
Network unreachable error while pulling from ECR

### ISSUE THREAD

**Issue by paul-civitas** [runfinch/finch#699]
**Describe the bug**

When attempting to pull an image from ECR, we get an network unreachable error.

```
seanchambers@MacBook-Pro .aws % finch pull 830786003228.dkr.ecr.us-east-1.amazonaws.com/inspire:8bdbe4b4acbbfe00d2079da763756fe224d60974
830786003228.dkr.ecr.us-east-1.amazonaws.com/inspire:8bdbe4b4acbbfe00d2079da763756fe224d60974: resolved    |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:dbd97a589135fa967daf69c13435067711a4c61ded7c08bf7e46fb597399e330:       done      |++++++++++++++++++++++++++++++++++++++| 
config-sha256:e8f0fa39c99204e633a8d02511d44a3def8528c33d2d85536c364748630edaaf:        downloading  |--------------------------------------|  0.0 B/20.8 KiB 
elapsed: 1.5 s                                         total: 6.6 Ki (4.4 KiB/s)                    
FATA[0001] failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://830786003228.dkr.ecr.us-east-1.amazonaws.com/v2/inspire/blobs/sha256:34606fd0a15d10779b9ea9595128ff911dd5fcd73f1108db4b07fddb34c79740": dial tcp 3.86.125.4:443: connect: network is unreachable 
FATA[0001] exit status 1
```

**Steps to reproduce**

I can not reproduce this issue on my computer, but two of my colleagues are having this issue.

**Expected behavior**

Image pulls successfully.

**Screenshots or logs**

Logs already attached.

**Additional context**

I'm on an m1 mac. My colleague is on an m2 mac. We're both using the arm64 version of finch, verified by running: `file -b $(which finch)`

I'm on Mac OS 14.0 they're on 13.4.

**Comment by sean-civitas** [comment]
[finch-support-20231116120608.zip](https://github.com/runfinch/finch/files/13381159/finch-support-20231116120608.zip)

attached support file

**Comment by paul-civitas** [comment]
I wonder if this is related: https://github.com/containerd/containerd/issues/7676

**Comment by vsiravar** [comment]
Thanks for trying finch. Is this observed only while pulling that particular image or is it a problem for any image that you try to pull from the registry?

**Comment by vsiravar** [comment]
> I wonder if this is related: [containerd/containerd#7676](https://github.com/containerd/containerd/issues/7676)

Does your image also contain nondistributable layers. A link to the Dockerfile or the layer that is failing would help in the debugging effort.

**Comment by paul-civitas** [comment]
I checked and it doesn't have any non distributable layers.

I might be able to get you the image in question through AWS support if you're an amazon employee.

**Comment by coderbirju** [comment]
Is this issue still persistent with the latest version of finch? 
Closing this issue, feel free to comment if this issue is reccurring.
