### ISSUE TITLE
Not working in Mac M2.

### ISSUE THREAD

**Issue by moolyasuresh** [runfinch/finch#782]
**Describe the bug**
Briefly describe the problem you are having.

Installed finch in Mac M2 but when i try to run finch --version , I get below error

 finch -version
M1 architecture detected. Installing aarch64 package.

INFO[0000] Using default values due to missing config file at "/Users/myusername/.finch/finch.yaml" 
INFO[0000] "/Users/myusername/.finch" directory doesn't exist, attempting to create it 
FATA[0000] unknown shorthand flag: 'e' in -ersion   

**Steps to reproduce**
A clear, step-by-step set of instructions to reproduce the bug.
toolbox install finch
finch --version

**Expected behavior**
Description of what you expected to happen.

**Screenshots or logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional context**

_To help debug the issue as quickly as possible, we recommend generating a support bundle with `finch support-bundle generate` and attaching it to this issue. This packages all Finch-related configs and logs into one file._

**Comment by AkihiroSuda** [comment]
Is this issue really specific to M2?

**Comment by moolyasuresh** [comment]
This is not an issue. There was a typo in my command
