### ISSUE TITLE
`compose exec` command is missing

### ISSUE THREAD

**Issue by KoichiKiyokawa** [runfinch/finch#79]
First, thank you for all of your works on finch.

**What is the problem you're trying to solve?.**
docker has `compose exec` command, but finch doesn't.
https://docs.docker.com/engine/reference/commandline/compose_exec/

**Describe the feature you'd like**
`finch compose exec` performs the same action as `docker compose exec`

**Comment by monirul** [comment]
finch uses `nerdctl` as upstream. Currently, `compose exec` is not supported by `nerdctl`
Here is the list of commands supported by `nerdctl` 
https://github.com/containerd/nerdctl#command-reference

**Comment by monirul** [comment]
@KoichiKiyokawa, Finch 0.2.0 uses nerdctl 1.1 which supports `compose exec` command.
example:
`finch compose exec service_name pwd`

**Comment by KoichiKiyokawa** [comment]
@monirul Thank you so much!  It helps me a lot!
