### ISSUE TITLE
Ability to copy files from the host inside a container

### ISSUE THREAD

**Issue by deviantony** [runfinch/finch#82]
**What is the problem you're trying to solve?.**
I'd like to copy some files from my host inside a container.

**Describe the feature you'd like**
The equivalent of `nerdctl cp` (https://github.com/containerd/nerdctl#whale-nerdctl-cp) available via `finch cp`. 

Alternatively, direct access to the nerdctl command for operations that are currently non supported by finch.

**Additional context**

**Comment by deviantony** [comment]
Well, this is actually hidden under `finch container cp`, maybe `finch cp` could be an alias for this to keep consistency across the CLI UX with nerdctl.

I'll leave that one open for you to decide :-)

**Comment by mharwani** [comment]
Hi @deviantony, thanks for the feedback. I agree that `finch cp` should be a valid command to keep consistency with `nerdctl`. I'm working on it.

**Comment by mharwani** [comment]
`finch cp` is available as of release [0.2.0](https://github.com/runfinch/finch/releases/tag/v0.2.0)

**Comment by mharwani** [comment]
`finch cp` is available as of release [0.2.0](https://github.com/runfinch/finch/releases/tag/v0.2.0)
