### ISSUE TITLE
Support --build-context for buildkit

### ISSUE THREAD

**Issue by DavidSouther** [runfinch/finch#821]
**What is the problem you're trying to solve?.**

Complex builds needing some, but not all, of the project layout. https://www.docker.com/blog/dockerfiles-now-support-multiple-build-contexts/

**Describe the feature you'd like**

Support for the --build-context flag on the `finch build` command.

**Additional context**

https://docs.docker.com/engine/reference/commandline/buildx_build/#build-context
https://docs.docker.com/build/building/context/
https://github.com/moby/buildkit/blob/34c8c96ff3002528ae7566354758b52e1f5a4bf8/frontend/attestations/sbom/sbom.go#L32

**Comment by mharwani** [comment]
Featured added in nerdctl: https://github.com/containerd/nerdctl/pull/2861. The issue can be closed.
