### ISSUE TITLE
SHA256 Mismatch Error When Installing Finch v1.1.3 via Homebrew

### ISSUE THREAD

**Issue by jacobcbeaudin** [runfinch/finch#884]
**Describe the bug**
During the installation of Finch v1.1.3 through Homebrew, I encountered a SHA256 mismatch error, preventing the successful completion of the installation.

**Steps to reproduce**
1. Execute `brew install finch` in the terminal.
2. The download initiates but fails, citing a SHA256 mismatch error.

**Expected behavior**
The Finch package should download and install without any errors, including SHA256 mismatches.

**Screenshots or logs**
```
$ brew install finch
==> Downloading https://github.com/runfinch/finch/releases/download/v1.1.3/Finch-v1.1.3-aarch64.pkg
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/562778457/04c827e9-e785
################################################################################################################## 100.0%
Error: SHA256 mismatch
Expected: ab04c7116e25babd9c3f97a71d6999851499108d62da5b74ba6f07613aea754b
  Actual: 5b338ec9482e6bacce44b64c332fbf031469cf4571336dbb47303ab13637cb18
    File: /Users/jacob/Library/Caches/Homebrew/downloads/969c63dfe4ed5c6841dfbb69b2201131b1b6bf36f8d059cf94939797ea89a6ca--Finch-v1.1.3-aarch64.pkg
To retry an incomplete download, remove the file above.
```

**Additional context**
This error appears to be a discrepancy between the expected and actual SHA256 checksums of the downloaded Finch package. I have tried removing the file mentioned in the error message and reattempting the installation, but the issue persists.

**Comment by bernardosw-aws** [comment]
Same issue here. Have manually downloaded the Finch-v1.1.3-aarch64.pkg and the sha256sum comes out exactly as the one shown above as "Actual".

**Comment by krehel** [comment]
Hi! - Homebrew maintainer here 👋 

Checksums are wrong on our side because the package was re-released a few days after our update with the same version number.  

Given heightened security these days...was this an intentional action / something was broken in the original package?Appreciate the Finch team chiming in and we'll patch up the Homebrew Cask.

Thanks everyone! 🍺

**Comment by Shubhranshu153** [comment]
Hi @krehel ,
So while running the release, the tag was set incorrectly to main instead of v1.1.3, so the new run was done. 
It was not done for security risk or anything broken with original package.

**Comment by krehel** [comment]
Thanks @Shubhranshu153 for confirming no issues.

**Comment by jacobcbeaudin** [comment]
https://github.com/Homebrew/homebrew-cask/pull/170355 resolved this issue
